### ISSUE TITLE
are you sure about the lines 53 and 54 in startup.cs ?

### ISSUE THREAD

**Issue by george-tsiros** [jesusvallejo/Midi2Vol#6]
because it looks like you compare

the same thing

**Comment by jesusvallejo** [comment]
will check it , but irc it checked if the current lauched is the found process. if not means there is already a running instace of the app.

As stated in your message it has no sense to compare the process id AND the path where the exe is runing. i presume i added this a long time ago to test on visual while actually using the app and forgot to remove it, already removed. thanks
